# Generated by Django 4.2.10 on 2026-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_length_alter_customer_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approval_status',
            field=models.CharField(default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(default='Approved', max_length=20),
        ),
    ]
