# Generated by Django 4.2.10 on 2026-05-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_approval_status_order_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(default='Approved', max_length=20),
        ),
    ]
