# Generated by Django 4.2.7 on 2026-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(default='Approved', max_length=20),
        ),
    ]
